name: Deploy Email Signature Generator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
  NODE_VERSION: '18'

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Type Check
      run: npm run check

    - name: Build Application
      run: npm run build
      env:
        NODE_ENV: production

    - name: Create PM2 ecosystem file
      run: |
        cat > ecosystem.config.cjs << EOF
        module.exports = {
          apps: [{
            name: 'email-signature',
            script: 'index.js',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            env: {
              NODE_ENV: 'production',
              PORT: 3000
            }
          }]
        }
        EOF

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Lightsail
      run: |
        # Deploy the application
        rsync -avz --delete ./dist/ ec2-user@${{ secrets.LIGHTSAIL_HOST }}:/home/ec2-user/app/
        
        # Copy package files and ecosystem config
        rsync -avz package.json package-lock.json ecosystem.config.cjs ec2-user@${{ secrets.LIGHTSAIL_HOST }}:/home/ec2-user/app/
        
        # Install production dependencies and restart application
        ssh ec2-user@${{ secrets.LIGHTSAIL_HOST }} "cd /home/ec2-user/app && \
          source ~/.nvm/nvm.sh && \
          npm ci --omit=dev && \
          pm2 restart email-signature || pm2 start ecosystem.config.cjs"

    - name: Verify Deployment
      run: |
        # Wait for the application to start
        sleep 10
        
        # Check if the application is responding
        curl --fail -H "Host: email.icebarrelautomations.com" http://${{ secrets.LIGHTSAIL_HOST }} || exit 1
