name: Deploy Email Signature Generator

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Application
      run: |
        # Build both client and server
        npm run build
        
        # Verify build output
        if [ ! -d "dist" ]; then
          echo "dist directory does not exist"
          exit 1
        fi
        
        # Check for both client and server builds
        if [ ! -d "dist/public" ]; then
          echo "dist/public directory does not exist"
          exit 1
        fi
        
        if [ ! -f "dist/index.js" ]; then
          echo "Server build (dist/index.js) does not exist"
          exit 1
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

    - name: Deploy to Lightsail
      run: |
        # Add Lightsail host to known_hosts
        ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts
        
        # Create deployment directory
        ssh ec2-user@${{ secrets.LIGHTSAIL_HOST }} "mkdir -p /home/ec2-user/email"
        
        # Install Node.js and npm if not already installed
        ssh ec2-user@${{ secrets.LIGHTSAIL_HOST }} "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && \
          source ~/.nvm/nvm.sh && \
          nvm install 18 && \
          nvm use 18"
        
        # Deploy entire dist folder (both client and server)
        rsync -avz --delete ./dist/ ec2-user@${{ secrets.LIGHTSAIL_HOST }}:/home/ec2-user/email/
        
        # Copy package files for production dependencies
        rsync -avz package.json package-lock.json ec2-user@${{ secrets.LIGHTSAIL_HOST }}:/home/ec2-user/email/
        
        # Install production dependencies on server
        ssh ec2-user@${{ secrets.LIGHTSAIL_HOST }} "source ~/.nvm/nvm.sh && cd /home/ec2-user/email && npm ci --production"
        
        # Restart the application (assuming you're using PM2 or similar)
        ssh ec2-user@${{ secrets.LIGHTSAIL_HOST }} "source ~/.nvm/nvm.sh && cd /home/ec2-user/email && pm2 restart email || pm2 start index.js --name 'email'"